/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Combustivel extends javax.swing.JFrame {

    /**
     * Creates new form Combustivel
     */
    public Combustivel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelCombustivel = new javax.swing.JLabel();
        jComboBoxCombustivel = new javax.swing.JComboBox<>();
        jLabelPrecoDoCombustivel = new javax.swing.JLabel();
        jTextFieldPrecoDoCombustivel = new javax.swing.JTextField();
        jLabelKmPorLitro = new javax.swing.JLabel();
        jTextFieldKmPorLitro = new javax.swing.JTextField();
        jLabelKmPercorrido = new javax.swing.JLabel();
        jTextFieldKmPercorridos = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 315));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitle.setText("Combustível");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabelCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCombustivel.setText("Combustível:");
        jPanel1.add(jLabelCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jComboBoxCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Gasolina", "Etanol", "Diesel" }));
        jComboBoxCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCombustivelActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 30));

        jLabelPrecoDoCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecoDoCombustivel.setText("Preço do Combustível:");
        jPanel1.add(jLabelPrecoDoCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jTextFieldPrecoDoCombustivel.setEditable(false);
        jPanel1.add(jTextFieldPrecoDoCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, 30));

        jLabelKmPorLitro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelKmPorLitro.setText("Km/Litro:");
        jPanel1.add(jLabelKmPorLitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel1.add(jTextFieldKmPorLitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 30));

        jLabelKmPercorrido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelKmPercorrido.setText("Km Percorrido");
        jPanel1.add(jLabelKmPercorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel1.add(jTextFieldKmPercorridos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 320, 30));

        jButtonCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCombustivelActionPerformed
        String tipoDeCombustivel = String.valueOf(jComboBoxCombustivel.getModel().getSelectedItem());
        
        if (tipoDeCombustivel == "Selecione") {
            jTextFieldPrecoDoCombustivel.setText("");
        }
        
        if (tipoDeCombustivel == "Gasolina") {
            jTextFieldPrecoDoCombustivel.setText("R$ 4,99");
        }
        
        if (tipoDeCombustivel == "Etanol") {
            jTextFieldPrecoDoCombustivel.setText("R$ 3,59");
        }
        
         if (tipoDeCombustivel == "Diesel") {
            jTextFieldPrecoDoCombustivel.setText("R$ 6,99");
        }
    }//GEN-LAST:event_jComboBoxCombustivelActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        double precoDoCombustivel = Double.parseDouble(jTextFieldPrecoDoCombustivel.getText().replace("R$ ", "").replace(",", "."));
        
        int kmPercorridos = Integer.parseInt(jTextFieldKmPercorridos.getText());
        int kmPorLitro = Integer.parseInt(jTextFieldKmPorLitro.getText());
        
        int litros = kmPercorridos / kmPorLitro;
        
        double preco = litros * precoDoCombustivel;
        
        JOptionPane.showMessageDialog(rootPane, String.format("R$ %.2f", preco));
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combustivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combustivel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox<String> jComboBoxCombustivel;
    private javax.swing.JLabel jLabelCombustivel;
    private javax.swing.JLabel jLabelKmPercorrido;
    private javax.swing.JLabel jLabelKmPorLitro;
    private javax.swing.JLabel jLabelPrecoDoCombustivel;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldKmPercorridos;
    private javax.swing.JTextField jTextFieldKmPorLitro;
    private javax.swing.JTextField jTextFieldPrecoDoCombustivel;
    // End of variables declaration//GEN-END:variables
}
