/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Chat extends javax.swing.JInternalFrame {

    /**
     * Creates new form Notas
     */
    public Chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelMensagem = new javax.swing.JLabel();
        jTextFieldMensagem = new javax.swing.JTextField();
        jButtonEnviarMensagem = new javax.swing.JButton();
        jLabelHistorico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitle.setText("WhatsApp");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabelMensagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMensagem.setText("Mensagem");
        jPanel1.add(jLabelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextFieldMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMensagemActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, 30));

        jButtonEnviarMensagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEnviarMensagem.setText("Enviar Mensagem");
        jButtonEnviarMensagem.setAlignmentY(0.0F);
        jButtonEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarMensagemActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEnviarMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 330, 40));

        jLabelHistorico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHistorico.setText("Histórico de Mensagens");
        jPanel1.add(jLabelHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMensagemActionPerformed

    
    private void jButtonEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarMensagemActionPerformed
        String mensagem = jTextFieldMensagem.getText();
        
        String mensagens = jTextArea1.getText();
    }//GEN-LAST:event_jButtonEnviarMensagemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarMensagem;
    private javax.swing.JLabel jLabelHistorico;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldMensagem;
    // End of variables declaration//GEN-END:variables
}
