/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class IMC extends javax.swing.JInternalFrame {

    /**
     * Creates new form Notas
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabelAltura = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitle.setText("Calcular IMC");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabelPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPeso.setText("Peso (kg):");
        jPanel1.add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, 30));

        jLabelAltura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAltura.setText("Altura (m):");
        jPanel1.add(jLabelAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));
        jPanel1.add(jTextFieldAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 30));

        jButtonCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        double peso = Double.parseDouble(jTextFieldPeso.getText());
        double altura = Double.parseDouble(jTextFieldAltura.getText());
        
        double imc = peso / (altura * altura);
        
        System.out.println(imc);
        
        JOptionPane.showMessageDialog(rootPane, String.format("O IMC de alguém que pesa %.2fkg e tem %.2fcm de altura é: %.2f", peso, altura, imc));
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldPeso;
    // End of variables declaration//GEN-END:variables
}
