package Formularios;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuNotas = new javax.swing.JMenuItem();
        openMenuTemperatura = new javax.swing.JMenuItem();
        openMenuIMC = new javax.swing.JMenuItem();
        openMenuCalculadora = new javax.swing.JMenuItem();
        openMenuChat = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Calcular");

        openMenuNotas.setMnemonic('o');
        openMenuNotas.setText("Notas");
        openMenuNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuNotasActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuNotas);

        openMenuTemperatura.setMnemonic('s');
        openMenuTemperatura.setText("Temperatura");
        openMenuTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuTemperaturaActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuTemperatura);

        openMenuIMC.setMnemonic('a');
        openMenuIMC.setText("IMC");
        openMenuIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuIMCActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuIMC);

        openMenuCalculadora.setMnemonic('x');
        openMenuCalculadora.setText("Calculadora");
        openMenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuCalculadoraActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuCalculadora);

        openMenuChat.setMnemonic('x');
        openMenuChat.setText("Chat");
        openMenuChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuChatActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuChat);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuCalculadoraActionPerformed
        Calculadora calculadora = new Calculadora();
        
        calculadora.setVisible(true);
        
        this.desktopPane.add(calculadora);
    }//GEN-LAST:event_openMenuCalculadoraActionPerformed

    private void openMenuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuNotasActionPerformed
        Notas notas = new Notas();
        
        notas.setVisible(true);
        
        this.desktopPane.add(notas);
    }//GEN-LAST:event_openMenuNotasActionPerformed

    private void openMenuTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuTemperaturaActionPerformed
        Temperatura temperatura = new Temperatura();
        
        temperatura.setVisible(true);
        
        this.desktopPane.add(temperatura);
    }//GEN-LAST:event_openMenuTemperaturaActionPerformed

    private void openMenuIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuIMCActionPerformed
        // TODO add your handling code here:
        IMC imc = new IMC();
        
        imc.setVisible(true);
        
        this.desktopPane.add(imc);
    }//GEN-LAST:event_openMenuIMCActionPerformed

    private void openMenuChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuChatActionPerformed
        Chat chat = new Chat();
        
        chat.setVisible(true);
        
        this.desktopPane.add(chat);
    }//GEN-LAST:event_openMenuChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuCalculadora;
    private javax.swing.JMenuItem openMenuChat;
    private javax.swing.JMenuItem openMenuIMC;
    private javax.swing.JMenuItem openMenuNotas;
    private javax.swing.JMenuItem openMenuTemperatura;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
