/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Temperatura extends javax.swing.JInternalFrame {

    /**
     * Creates new form Notas
     */
    public Temperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelTemperatura = new javax.swing.JLabel();
        jTextFieldTemperatura = new javax.swing.JTextField();
        jButtonConverter = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelTitle.setText("Conveter Celsius para Fahrenheit");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabelTemperatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTemperatura.setText("Temperatura (°C):");
        jPanel1.add(jLabelTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextFieldTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, 30));

        jButtonConverter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonConverter.setText("Converter");
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        // TODO add your handling code here:
        double celsius = Double.parseDouble(jTextFieldTemperatura.getText());

        double fahrenheit = (celsius * (9 / 5)) + 32;

        JOptionPane.showMessageDialog(rootPane, String.format("A temperatura %.2f°C em celsius é igual a %.2f°F", celsius, fahrenheit));

    }//GEN-LAST:event_jButtonConverterActionPerformed

    private void jTextFieldTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTemperaturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JLabel jLabelTemperatura;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldTemperatura;
    // End of variables declaration//GEN-END:variables
}
