/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aulas;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class MediaAutomatica extends javax.swing.JFrame {

    /**
     * Creates new form Media
     */
    public MediaAutomatica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelNota1 = new javax.swing.JLabel();
        jTextFieldNota1 = new javax.swing.JTextField();
        jLabelNota2 = new javax.swing.JLabel();
        jTextFieldNota2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitle.setText("Cálculo de Média");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabelNota1.setText("Nota 1:");
        jPanel1.add(jLabelNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jTextFieldNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNota1ActionPerformed(evt);
            }
        });
        jTextFieldNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNota1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNota1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 30));

        jLabelNota2.setText("Nota 2:");
        jPanel1.add(jLabelNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jTextFieldNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNota2ActionPerformed(evt);
            }
        });
        jTextFieldNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNota2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNota2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Média:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNota1ActionPerformed

    private void jTextFieldNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNota2ActionPerformed

    private void jTextFieldNota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNota1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNota1KeyTyped

    private void jTextFieldNota2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNota2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNota2KeyTyped

    private void jTextFieldNota1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNota1KeyReleased
        // TODO add your handling code here:
        try {
            String nota1 = jTextFieldNota1.getText();
            String nota2 = jTextFieldNota2.getText();

            if (nota1 != "" && nota2 != "") {
                double media = (Double.parseDouble(nota1) + Double.parseDouble(nota2)) / 2;

                jLabel1.setText(String.format("Média: %.2f", media));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldNota1KeyReleased

    private void jTextFieldNota2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNota2KeyReleased
        // TODO add your handling code here:
        try {
            String nota1 = jTextFieldNota1.getText();
            String nota2 = jTextFieldNota2.getText();

            if (nota1 != "" && nota2 != "") {
                double media = (Double.parseDouble(nota1) + Double.parseDouble(nota2)) / 2;

                jLabel1.setText(String.format("Média: %.2f", media));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldNota2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediaAutomatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediaAutomatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediaAutomatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediaAutomatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediaAutomatica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNota1;
    private javax.swing.JLabel jLabelNota2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNota1;
    private javax.swing.JTextField jTextFieldNota2;
    // End of variables declaration//GEN-END:variables
}
